# Generated by Django 4.2.5 on 2023-09-25 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('tuID', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('add', models.TextField()),
                ('fee', models.CharField(max_length=20)),
                ('add_n', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nic', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('add', models.TextField()),
                ('pas', models.CharField(max_length=1000)),
                ('pic', models.ImageField(upload_to='images/')),
                ('qua', models.CharField(max_length=250)),
                ('inst', models.CharField(max_length=250)),
                ('approval', models.IntegerField()),
                ('exp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval', models.IntegerField()),
                ('tution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.contactus')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.tutor')),
            ],
        ),
    ]
