# Generated by Django 4.2.5 on 2023-09-25 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_contactus_date_tutor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 14, 53, 12, 904291)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 14, 53, 12, 951176)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
