# Generated by Django 4.2.5 on 2023-09-25 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_alter_contactus_date_alter_tutor_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='about',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 17, 24, 52, 44273)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 17, 24, 52, 77267)),
        ),
    ]
