# Generated by Django 4.2.5 on 2023-09-25 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_contactus_date_alter_tutor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 20, 52, 6, 58163)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 25, 20, 52, 6, 111962)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='pic',
            field=models.ImageField(default='static/images/profile.jpg', upload_to='images/'),
        ),
    ]
