# Generated by Django 4.2.5 on 2023-09-26 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_tutor_ach_tutor_sub_alter_contactus_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 26, 13, 0, 28, 771175)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 26, 13, 0, 28, 818047)),
        ),
    ]
