# Generated by Django 4.2.5 on 2023-09-26 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_contactus_date_alter_tutor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 26, 14, 58, 9, 698703)),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 9, 26, 14, 58, 9, 745575)),
        ),
    ]
